services:
  - type: web
    name: friendly-app
    env: node
    buildCommand: npm install && npm run build && cd server && npm install && npm run build
    startCommand: cd server && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
